Repository ishangoyal13/fullstackDevelopment, pull requests merged in 2022-10, with the labels that each got.

#595 Created Bash Scripts
  Bash/hello_world.sh
Labels: help wanted, hacktoberfest-accepted

#560 Lowest Common Ancestor of Deepest Leaves
  C++/Lowest Common Ancestor of Deepest Leaves.cpp
Labels: hacktoberfest-accepted

#533 ✨ Lowest Common Ancestors in Python Added
  Python/Lowest Common Ancestors.py
Labels: hacktoberfest-accepted, hacktoberfest
